### ISSUE TITLE
Create a html page for the demo

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/quran-verse-detection#2]
create a html page for [demo](https://codepen.io/fawazahmed0/pen/oNbZbRb?editors=1111) where users can paste the quranic text in input and click submit & it will print the chapter number & verse number of the quranic text

**Comment by rodgeraraujo** [comment]
Can I work on this?

**Comment by fawazahmed0** [comment]
> Can I work on this?

Yes, I have assigned this task to you
